######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 18:15:57 2017
######################################################################

QT += widgets testlib
TEMPLATE = app
CONFIG   += c++11
TARGET = test
CONFIG   += c++11
INCLUDEPATH += .

# Input
HEADERS += headers/generateprimes.h\
        headers/hash.h \
        headers/cryptogame.h \
        headers/sha512.h \
        headers/md5.h \
        headers/pbkdf2.h \
        headers/crack.h \
    headers/bruteforcecrack.h \
    headers/dictionarycrack.h \
    headers/bruteforcefactor.h \
    headers/buttonarray.h \
    headers/factor.h \
    headers/cipher.h \
    headers/mainwindow.h

SOURCES  += testcipher.cpp \
        src/generateprimes.cpp\
        src/hash.cpp \
        src/cryptogame.cpp \
        src/sha512.cpp \
        src/md5.cpp \
        src/pbkdf2.cpp \
    src/crack.cpp \
    src/bruteforcecrack.cpp \
    src/dictionarycrack.cpp \
    src/factor.cpp \
    src/bruteforcefactor.cpp \
    src/cipher.cpp \
    src/buttonarray.cpp \
    src/mainwindow.cpp


unix:{  LIBS	 += -L/usr/local/lib \
                    -lgmp \
                    -lgmpxx \
                    -lcryptopp

}
