######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 18:15:57 2017
######################################################################

QT += widgets testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += testcipher.cpp

HEADERS  += headers/mainwindow.h\
        headers/generateprimes.h\
        headers/hash.h \
        headers/cryptogame.h \
        headers/sha512.h \
        headers/md5.h \
        headers/pbkdf2.h \
        headers/crack.h \
    headers/bruteforcecrack.h \
    headers/dictionarycrack.h \
    headers/bruteforcefactor.h \
    headers/factor.h \
    ../headers/cipher.h
