######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 18:15:57 2017
######################################################################

QT += widgets testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += testcipher.cpp \
        ../src/cipher.cpp

HEADERS  += ../headers/cipher.h
